export {default as About} from './about/About'
export {default as Contact} from './contact/Contact'
export {default as Intro} from './intro/Intro'
export {default as ProductList} from './productList/ProductList'
export {default as Toggle} from './toggle/Toggle'